// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package umlxmi2pt1


case class Model2(packagedElement: umlxmi2pt1.PackagedElement,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val name = attributes("@name").as[String]
  lazy val visibility = attributes("@visibility").as[String]
  lazy val xmitype = attributes("@{http://schema.omg.org/spec/XMI/2.1}type").as[String]
}

      

