// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package umlxmi2pt1


case class XMI(Documentation: umlxmi2pt1.Documentation2,
  Model: umlxmi2pt1.Model2,
  Extension: umlxmi2pt1.Extension,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val xmiversion = attributes("@{http://schema.omg.org/spec/XMI/2.1}version").as[BigDecimal]
}

      


case class Documentation2(attributes: Map[String, scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val exporter = attributes("@exporter").as[String]
  lazy val exporterID = attributes("@exporterID").as[BigInt]
  lazy val exporterVersion = attributes("@exporterVersion").as[BigDecimal]
}

      


case class Extension(attributes: Map[String, scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val extender = attributes("@extender").as[String]
  lazy val extenderID = attributes("@extenderID").as[BigDecimal]
}

      

