# Make generalization triples
INSERT  {
        GRAPH <http://data.pg.com/data/graph/DATA_CSM_Instances_v2_union> {
        ?subjectURI pgont:generalization ?objectURI .
        }
}
WHERE {
{
SELECT ?gen (GROUP_CONCAT(?relation ; separator= "|") AS ?subobj)
WHERE {
{
SELECT ?gen ?baseEndID ?derivedEndID ?relation
WHERE {
        ?gen a csmi:IGeneralization .
        ?gen csmi:aggregatesListRef/csmi:value ?genaggid .
        BIND (  dash:toString(?genaggid) AS ?genaggidstr) .

        OPTIONAL {
        ?genaggidstr ^(csmi:_idRef/dtype:value) ?baseEnd .
        ?baseEnd rdf:type csmi:ITag .
        ?baseEnd csmi:_nameRef/dtype:value "BaseEnd" .
        ?baseEnd csmi:aggregatesListRef/csmi:value ?baseEndAggID .
        BIND (  dash:toString(?baseEndAggID) AS ?baseEndAggIDstr) .
        ?baseEndAggIDstr ^(csmi:_idRef/dtype:value) ?baseEndLitSpec .
        ?baseEndLitSpec rdf:type csmi:ILiteralSpecification .
        ?baseEndLitSpec csmi:_valueRef/dtype:value ?baseEndID .
        BIND ( fn:concat("OBJ:", ?baseEndID) AS ?relation)
        }
        OPTIONAL {
        ?genaggidstr ^(csmi:_idRef/dtype:value) ?derivedEnd .
        ?derivedEnd rdf:type csmi:ITag .
        ?derivedEnd csmi:_nameRef/dtype:value "DerivedEnd" .
        ?derivedEnd csmi:aggregatesListRef/csmi:value ?derivedEndAggID .
        BIND (  dash:toString(?derivedEndAggID) AS ?derivedEndAggIDstr) .
        ?derivedEndAggIDstr ^(csmi:_idRef/dtype:value) ?derivedEndLitSpec .
        ?derivedEndLitSpec rdf:type csmi:ILiteralSpecification .
        ?derivedEndLitSpec csmi:_valueRef/dtype:value ?derivedEndID .
        BIND ( fn:concat("SUB:", ?derivedEndID) AS ?relation)
        }

        FILTER (BOUND(?baseEndID) || BOUND(?derivedEndID)) .
}
}
} GROUP BY ?gen }
        BIND (spif:regex(?subobj, "^OBJ:([a-zA-Z0-9- ]*)\\|SUB:([a-zA-Z0-9- ]*)$", "$2") AS ?subject)
        BIND (spif:regex(?subobj, "^OBJ:([a-zA-Z0-9- ]*)\\|SUB:([a-zA-Z0-9- ]*)$", "$1") AS ?object)
        BIND (spif:replaceAll(?subject, ' ', '_') AS ?subjectguid) .
        BIND (spif:replaceAll(?object, ' ', '_') AS ?objectguid) .
        BIND (spif:buildURI("http://data.pg.com/data/{?subject}") AS ?subjectURI) .
        BIND (spif:buildURI("http://data.pg.com/data/{?object}") AS ?objectURI) .
        }